services:
  postgres:
    image: postgres:16-alpine
    container_name: cdc-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: financeiro
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=10"
      - "-c"
      - "max_wal_senders=10"
    volumes:
      - ./init-postgres-1.sql:/docker-entrypoint-initdb.d/init-postgres-1.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d financeiro"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-2:
    image: postgres:16-alpine
    container_name: cdc-postgres-2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: pagamentos
    ports:
      - "5433:5432"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=10"
      - "-c"
      - "max_wal_senders=10"
    volumes:
      - ./init-postgres-2.sql:/docker-entrypoint-initdb.d/init-postgres-2.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d pagamentos"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-3:
    image: postgres:16-alpine
    container_name: cdc-postgres-3
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: rh
    ports:
      - "5434:5432"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=10"
      - "-c"
      - "max_wal_senders=10"
    volumes:
      - ./init-postgres-3.sql:/docker-entrypoint-initdb.d/init-postgres-3.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d rh"]
      interval: 5s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.0
    container_name: cdc-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: financeiro
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin_password
    ports:
      - "3306:3306"
    command:
      --default-authentication-plugin=mysql_native_password
      --server-id=1
      --binlog-format=ROW
      --binlog-row-image=FULL
    volumes:
      - ./init-mysql-1.sql:/docker-entrypoint-initdb.d/init-mysql-1.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  mysql-2:
    image: mysql:8.0
    container_name: cdc-mysql-2
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin_password
    ports:
      - "3307:3306"
    command:
      --default-authentication-plugin=mysql_native_password
      --server-id=2
      --binlog-format=ROW
      --binlog-row-image=FULL
    volumes:
      - ./init-mysql-2.sql:/docker-entrypoint-initdb.d/init-mysql-2.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  mysql-3:
    image: mysql:8.0
    container_name: cdc-mysql-3
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: crm
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin_password
    ports:
      - "3308:3306"
    command:
      --default-authentication-plugin=mysql_native_password
      --server-id=3
      --binlog-format=ROW
      --binlog-row-image=FULL
    volumes:
      - ./init-mysql-3.sql:/docker-entrypoint-initdb.d/init-mysql-3.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  oracle-cdc:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: oracle-cdc
    environment:
      - ORACLE_PASSWORD=admin_password
      - ORACLE_DATABASE=ORCLPDB1
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: cdc-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT_INTERNAL'

      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: cdc-kafka-ui
    ports:
      - "8090:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=CDC-Local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    depends_on:
      - kafka

  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: cdc-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:10.4.2
    container_name: cdc-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

volumes:
    oracle-data: