SELECT name, open_mode, log_mode FROM v$database;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
CREATE USER C##CDC_USER IDENTIFIED BY cdc_password CONTAINER=ALL;
GRANT CREATE SESSION, ALTER SESSION, SET CONTAINER TO C##CDC_USER CONTAINER=ALL;
GRANT LOGMINING TO C##CDC_USER CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO C##CDC_USER CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_LOGMNR TO C##CDC_USER CONTAINER=ALL;
GRANT SELECT ON SYS.V_$LOGMNR_CONTENTS TO C##CDC_USER CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DATABASE TO C##CDC_USER CONTAINER=ALL;
GRANT SELECT ON SYS.V_$LOGMNR_LOGS TO C##CDC_USER CONTAINER=ALL;
GRANT SELECT ON SYS.V_$LOG TO C##CDC_USER CONTAINER=ALL;
GRANT SELECT ON SYS.V_$LOGFILE TO C##CDC_USER CONTAINER=ALL;
GRANT SELECT ON SYS.V_$ARCHIVED_LOG TO C##CDC_USER CONTAINER=ALL;

-- Setup in PDB
ALTER SESSION SET CONTAINER = ORCLPDB1;
CREATE USER RH IDENTIFIED BY rh_password;
GRANT CREATE SESSION, CREATE TABLE, UNLIMITED TABLESPACE TO RH;

CREATE TABLE RH.FUNCIONARIOS (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100),
    CARGO VARCHAR2(100),
    DEPARTAMENTO VARCHAR2(100)
);

ALTER TABLE RH.FUNCIONARIOS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
GRANT SELECT ON RH.FUNCIONARIOS TO C##CDC_USER;

INSERT INTO RH.FUNCIONARIOS (ID, NOME, CARGO, DEPARTAMENTO) VALUES (158, 'Leonardo Ramos', 'Estagiario', 'Inteligencia');
COMMIT;
EXIT;
