ALTER SESSION SET CONTAINER = ORCLPDB1;

-- 1. Schema RH
CREATE USER RH IDENTIFIED BY rh_password;
GRANT CREATE SESSION, CREATE TABLE, UNLIMITED TABLESPACE TO RH;
CREATE TABLE RH.FUNCIONARIOS (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100),
    CARGO VARCHAR2(100),
    DEPARTAMENTO VARCHAR2(100)
);
ALTER TABLE RH.FUNCIONARIOS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
GRANT SELECT ON RH.FUNCIONARIOS TO C##CDC_USER;
INSERT INTO RH.FUNCIONARIOS (ID, NOME, CARGO, DEPARTAMENTO) VALUES (1, 'Gestor RH', 'Diretor', 'RH');

-- 2. Schema FINANCEIRO
CREATE USER FINANCEIRO IDENTIFIED BY fin_password;
GRANT CREATE SESSION, CREATE TABLE, UNLIMITED TABLESPACE TO FINANCEIRO;
CREATE TABLE FINANCEIRO.LANCAMENTOS (
    ID NUMBER PRIMARY KEY,
    DESCRICAO VARCHAR2(100),
    VALOR NUMBER(15, 2),
    STATUS VARCHAR2(20)
);
ALTER TABLE FINANCEIRO.LANCAMENTOS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
GRANT SELECT ON FINANCEIRO.LANCAMENTOS TO C##CDC_USER;
INSERT INTO FINANCEIRO.LANCAMENTOS (ID, DESCRICAO, VALOR, STATUS) VALUES (1, 'Aporte Inicial', 50000.00, 'CONFIRMADO');

-- 3. Schema PATRIMONIO
CREATE USER PATRIMONIO IDENTIFIED BY pat_password;
GRANT CREATE SESSION, CREATE TABLE, UNLIMITED TABLESPACE TO PATRIMONIO;
CREATE TABLE PATRIMONIO.BENS (
    ID NUMBER PRIMARY KEY,
    CODIGO VARCHAR2(50),
    DESCRICAO VARCHAR2(100),
    VALOR NUMBER(15, 2)
);
ALTER TABLE PATRIMONIO.BENS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
GRANT SELECT ON PATRIMONIO.BENS TO C##CDC_USER;
INSERT INTO PATRIMONIO.BENS (ID, CODIGO, DESCRICAO, VALOR) VALUES (1, 'PAT-001', 'Servidor Blade Dell', 35000.00);

-- 4. Schema AUDITORIA
CREATE USER AUDITORIA IDENTIFIED BY aud_password;
GRANT CREATE SESSION, CREATE TABLE, UNLIMITED TABLESPACE TO AUDITORIA;
CREATE TABLE AUDITORIA.REGISTROS (
    ID NUMBER PRIMARY KEY,
    USUARIO VARCHAR2(50),
    ACAO VARCHAR2(100),
    STATUS VARCHAR2(20)
);
ALTER TABLE AUDITORIA.REGISTROS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
GRANT SELECT ON AUDITORIA.REGISTROS TO C##CDC_USER;
INSERT INTO AUDITORIA.REGISTROS (ID, USUARIO, ACAO, STATUS) VALUES (1, 'admin_sec', 'LOGIN_PORTAL', 'SUCESSO');

-- 5. Schema CONTRATOS
CREATE USER CONTRATOS IDENTIFIED BY con_password;
GRANT CREATE SESSION, CREATE TABLE, UNLIMITED TABLESPACE TO CONTRATOS;
CREATE TABLE CONTRATOS.ACORDOS (
    ID NUMBER PRIMARY KEY,
    NUMERO VARCHAR2(50),
    FORNECEDOR VARCHAR2(100),
    VALOR NUMBER(15, 2)
);
ALTER TABLE CONTRATOS.ACORDOS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
GRANT SELECT ON CONTRATOS.ACORDOS TO C##CDC_USER;
INSERT INTO CONTRATOS.ACORDOS (ID, NUMERO, FORNECEDOR, VALOR) VALUES (1, 'AC-2026/01', 'Tech Solucoes', 120000.00);

COMMIT;
EXIT;
