ALTER SESSION SET CONTAINER = ORCLPDB1;
INSERT INTO RH.FUNCIONARIOS (ID, NOME, CARGO, DEPARTAMENTO) VALUES (159, 'Ana Beatriz', 'Desenvolvedora', 'Tecnologia');
COMMIT;
UPDATE RH.FUNCIONARIOS SET CARGO = 'Arquiteta' WHERE ID = 159;
COMMIT;
EXIT;
