spring.application.name=rootL_cdcPublisher
server.port=8080

cdc.offset-dir=./offsets

kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}